
#portal-block-type-list:
#  - "minecraft:nether_portal"
#  - "minecraft:respawn_anchor"
  
#portal-vertical-block-type: "minecraft:nether_portal"
#portal-horizontal-block-type: "minecraft:respawn_anchor"

portal-block-type-list:
  - "minecraft:light"
  
portal-vertical-block-type: "minecraft:light"
portal-horizontal-block-type: "minecraft:light"

igniter-operation-costs:
    bind-to-eye: 2
    bind-to-dye: 2
    bind-to-diamond: 5
    bind-to-netherite: 15
    bind-to-redstone: 10