name: PaperPortals
version: "26.2"
main: com.tubba.mc.paper.portals.PortalPowerPlugin
api-version: "26.2"
description: Handles portals and stuff.
commands:
    portpower:
        description: Paper Portal Power commands
        usage: /paperport <subcommand>